### ISSUE TITLE
Unable to convert self-referring instances to resources

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-hal#1]
- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently.
  - [x] Detail the original, incorrect behavior.
  - [x] Detail the new, expected behavior.
  - [x] Base your feature on the `master` branch, and submit against that branch.
  - [x] Add a regression test that demonstrates the bug, and proves the fix.
  - [ ] Add a `CHANGELOG.md` entry for the fix.

Imagine the following example:
```php
class Parent {
    /** @var Child[] */
    public $childs;
    public function addChild(Child $child) {
        $this->childs[] = $child;
        $child->parent = $this;
    }
}
class Child {
    /** @var Parent */
    public $parent;
}

$parent = new Parent();
$parent->addChild(new Child());
$parent->addChild(new Child());

$generator->fromObject($parent, $request);
// the call above will result in an error:
// Error : Maximum function nesting level of '256' reached, aborting!
```

Other examples:
[One-To-One, Bidirectional](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-one-bidirectional)
[One-To-One, Self-referencing](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-one-self-referencing)
[One-To-Many, Bidirectional](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-many-bidirectional)
[One-To-Many, Self-referencing](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-many-self-referencing)
[Many-To-Many, Bidirectional](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#many-to-many-bidirectional)
[Many-To-Many, Self-referencing](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#many-to-many-self-referencing)

The zfcampus/zf-hal component solved this issue by using a `$maxDepth` [property in metadata](https://github.com/zfcampus/zf-hal/blob/master/src/Metadata/Metadata.php#L119) which is then passed through [here](https://github.com/zfcampus/zf-hal/blob/master/src/Plugin/Hal.php#L647) and [here](https://github.com/zfcampus/zf-hal/blob/master/src/Plugin/Hal.php#L674).

Using this approach would result in a change of the `\Zend\Expressive\Hal\ResourceGenerator\StrategyInterface` interface which would be a BC break.

I would love if someone comes up with an alternate solution which will not break BC.

---

Originally posted by @tobias-trozowski at https://github.com/zendframework/zend-expressive-hal/pull/57

**Comment by weierophinney** [comment]
still smells. but should fit now.

---

Originally posted by @tobias-trozowski at https://github.com/zendframework/zend-expressive-hal/pull/57#issuecomment-486763165

**Comment by weierophinney** [comment]
@tobias-trozowski I've rebased your branch to squash several commits and remove both the revert commits and the commits they were reverting; the diff ends up the same as you had committed previously.

In the future, feel free to use `git rebase -i` + `git push -f` liberally when working on a patch; these help ensure the history is easier to follow, particularly when removing patches.

I'll review again now to see where we are in terms of ability to merge.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-expressive-hal/pull/57#issuecomment-491986956

**Comment by guliano** [comment]
Any news on this issue?

**Comment by weierophinney** [comment]
@guliano Not yet. We're still finishing out tasks related to the Laminas migration, so it may be a few weeks.
