### ISSUE TITLE
Unable to generate HAL from proxy

### ISSUE THREAD

**Issue by alexmerlin** [mezzio/mezzio-hal#10]
Having an issue generating HAL response when a collection/entity contains proxies instead of their equivalent entities. I've found a discussion related to this [here](https://discourse.laminas.dev/t/synergy-of-proxy-object-of-doctrine-and-zend-expressive-hal/575/7), but the provided solutions don't seem to fix the issue.
Is there a workaround for this?
We've made a fork in which at `MetadataMap->__construct()` we're pushing the entities to `MetadataMap->$map` to make sure that `MetadataMap->has($class)` looks for and finds the entities and not their proxies, but this does not seem to be the correct approach to the issue.

**Comment by tobias-trozowski** [comment]
fixed in https://github.com/mezzio/mezzio-hal/releases/tag/2.1.0
