### ISSUE TITLE
Fast route with two placeholders

### ISSUE THREAD

**Issue by arstom** [mezzio/mezzio-hal#14]
Already opened a similar discussion on https://discourse.laminas.dev/t/fast-route-with-two-placeholders/1403

Solution would be:

RouteBasedResourceStrategy.php

```
if (isset($data[$resourceIdentifier])) {
    $routeParams[$routeIdentifier] = $data[$resourceIdentifier];
}

// Auto inject all entity keys in route params
foreach($data as $key => $value) {
    $routeParams[$key] = $value;
}
```

**Comment by froschdesign** [comment]
Reference:

https://github.com/mezzio/mezzio-hal/blob/f5cccc0c48ac6ba317adbdd8cdd6ec8c82ad01a3/src/ResourceGenerator/RouteBasedResourceStrategy.php#L45-L56

**Comment by weierophinney** [comment]
This is not specific to FastRoute; it's relevant to all the various routers, and I've run into it before.

You _can_ get them rendered with existing functionality, but it requires updating the metadata for the resource prior to generating it:

```php
$params = $request->getAttribute(RouteResult::class)->getMatchedParam();
$metadata = $resourceGenerator->getMetadataMap()->get(YourResourceType::class);
$metadata->setRouteParams($params);
$resource = $resourceGenerator->fromObject($instanceOfYourResourceType, $request);
```

The above assumes you are using one of the `RouteBased*` metadata types for that resource type.

If you're willing to create a patch that does what you note above, that would be great; that's a better place to do it (metadata should be idempotent!).

**Comment by arstom** [comment]
Thanks for your feedback. Yes, I will go for a patch.
