### ISSUE TITLE
Option to avoid structure equivalence check

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-hal#2]
I suspect that sometimes it would be nice to have the option to skip the check provided by the `HalResource::compareResources` method.

This is because sometimes resources could have optional fields, or because an embedded resource makes sense only in certain cases

---

Originally posted by @marcosh at https://github.com/zendframework/zend-expressive-hal/issues/54

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
