### ISSUE TITLE
Exposed embedded key existence in HalResource, added a test to check …

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-hal#3]
Provide a narrative description of what you are trying to accomplish:

- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently.
  - [x] Detail the original, incorrect behavior.
  - [x] Detail the new, expected behavior.
  - [x] Base your feature on the `master` branch, and submit against that branch.
  - [x] Add a regression test that demonstrates the bug, and proves the fix.
  - [ ] Add a `CHANGELOG.md` entry for the fix.

See https://github.com/zendframework/zend-expressive-hal/issues/52 for details

---

Originally posted by @jguittard at https://github.com/zendframework/zend-expressive-hal/pull/53

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
