### ISSUE TITLE
`HalResource` does not allow `_embed` data that is based on a `oneOf:` JSONSchema definition

### ISSUE THREAD

**Issue by Ocramius** [mezzio/mezzio-hal#50]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.3.1

#### Summary

This is a union of `Foo` and `Tab` in a JSONSchema resource:

```json
{
  "components": {
    "SomeResource": {
      "oneOf": [
        {"$ref": "#/components/Foo"},
        {"$ref": "#/components/Tab"}
      ]
    },
    "Foo": {
      "type": "object",
      "required": ["bar"],
      "properties": {
        "bar": {"type": "string"}
      }
    },
    "Tab": {
      "type": "object",
      "required": ["taz"],
      "properties": {
        "taz": {"type": "string"}
      }
    }
  }
}
```

In practice, when rendering a `list<SomeResource>`, you will get an array of JSON objects with different properties:

```json
[
  {"bar": "haha"},
  {"taz": "hehe"},
  {"bar": "hihi"}
]
```

#### Current behavior

`HalResource#__construct()` does some pretty aggressive validation of its JSON contents, specifically on `$embedded` data:

https://github.com/mezzio/mezzio-hal/blob/29f006b1da4e5d60d023c953bba4d21420459877/src/HalResource.php#L512-L529

This precludes usage of well-documented resources of different types.

#### How to reproduce

 * configure a resource for `class Foo { public string $bar = 'baz'; }`
 * configure a resource for `class Tab { public string $taz = 'tar'; }`
 * render a (pseudo-code) `new HalResource(..., ..., [new Foo(), new Tab()])` - it will crash due to `Foo` and `Tab` not sharing same properties

#### Expected behavior

A `HalResource` can be instantiated with `$embedded` data of different types:

https://github.com/mezzio/mezzio-hal/blob/29f006b1da4e5d60d023c953bba4d21420459877/src/HalResource.php#L52-L54

## Suggested solution

Let's just drop the exception: it was seemingly designed to support developers that have difficulty with keeping their data consistent, but it hinders proper union type design.

**Comment by weierophinney** [comment]
My understanding of how embedded collections work in HAL is that a collection (an `_embedded` item with an array of resources) is expected to contain resources that are all of the same type.

Interestingly, on reviewing the [current draft of the specification](https://datatracker.ietf.org/doc/html/draft-kelly-json-hal), there is no mention of this, which either means this has changed during draft evolution, or my understanding was based on participation in the HAL forums "back in the day".

As such, the only thing that is really required is that each item in the array is a _resource_ (i.e., an object with a Link collection). 

Totally willing and ready to review a patch that does this.

**Comment by Ocramius** [comment]
@Lucian-Olariu I can send this patch, FWIW 👍

**Comment by Ocramius** [comment]
@weierophinney even if they had the same type, a union type is indeed a valid type, heh 😁

**Comment by weierophinney** [comment]
Never thought I'd see the day you'd advocate for union types, @Ocramius . :smile:

**Comment by cronlabspl** [comment]
@weierophinney I also advocate for them.
