### ISSUE TITLE
Syntax Highlight on Documentation is "broken"

### ISSUE THREAD

**Issue by dmetzler1988** [mezzio/mezzio-hal#54]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.3.0

#### Summary

The syntax highlight in this documentation have an issue. The background is black and the text is also black - so we can't read something. It only works correctly on the index page, but not on each other sites.
Maybe an issue occured whilst building the documentation page. The Markdown files seems to be OK.

#### Current behavior

PHP Code is not readable on documentation.

#### How to reproduce

Simple check the documentation pages - like https://docs.mezzio.dev/mezzio-hal/v2/hal/

#### Expected behavior

Code is readable again

![image](https://user-images.githubusercontent.com/8446518/172777098-1e9af649-513a-466c-a47b-de19bf2bf4a3.png)

**Comment by froschdesign** [comment]
@weierophinney 
Please have a look at this.

**Comment by weierophinney** [comment]
Tried triggering a rebuild - the logs are reporting permissions issues, and I'm not sure if that's because triggering via a respository_dispatch doesn't load secrets, or if there's an issue with the tokens we have on this repository. :frowning_face:

**Comment by froschdesign** [comment]
Unfortunately, the search for the error took a very long time. However, the problem has now been solved.

@dmetzler1988 
Thanks for reporting the problem!
